version: '3.7'
services:
  registry:
    image: registry:2
    networks:
      - factory-plus
    deploy:
      placement:
        constraints:
          - node.hostname == amrc-factoryP-1
      restart_policy:
        condition: on-failure
        delay: 5s
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/amrc-factoryplus_shef_ac_uk.crt
      REGISTRY_HTTP_TLS_KEY: /certs/amrc-factoryplus_shef_ac_uk.key
    volumes:
      - /registry/data:/var/lib/registry
      - /etc/ssl:/certs

  docker-registry-browser:
    image: klausmeyer/docker-registry-browser
    networks:
      - factory-plus
    deploy:
      placement:
        constraints:
          - node.hostname == amrc-factoryP-1
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.registry.rule=Host(`registry.amrc-factoryplus.shef.ac.uk`)"
        - "traefik.docker.network=factory-plus"
        - "traefik.http.services.registry.loadbalancer.server.port=8080"
        - "traefik.http.routers.registry.tls=true"
    environment:
        - 'DOCKER_REGISTRY_URL=https://amrc-factoryplus.shef.ac.uk:5000'
networks:
  factory-plus:
    external: true
    name: factory-plus
